### ISSUE TITLE
This is Unrelated to the repo but I want to ask some questions

### ISSUE THREAD

**Issue by herfdiug** [lokzz/pylibrary#1]
Hello, you might not know me but I'd like to get in contact to ask about the FFlags you found and commented in a Bloxstrap issues thread, how did you find these particular set? Do you have any more? I'd figure it'd be more suitable if you can add me on Discord so we can discuss further, please at least respond to this so I am not left hanging!! Thank you so much. My discord tag is herfdiug

**Comment by lokzz** [comment]
1. the flags were in a roblox reversing discord server
2. and no, sorry i don't have anymore flags
